apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seyi-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/olagunjuraman/vpd-cd
    targetRevision: HEAD
    path: develop
    kustomize:
       namePrefix: dev-
  destination: 
    server: https://kubernetes.default.svc
    namespace: vpd-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true