apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vpd
resources:
- deployment.yml
- service.yml
- configmap.yml
- ingress.yml
images:
- name: seyi-api
  newName: 271365062139.dkr.ecr.us-east-1.amazonaws.com/vpd-api
  newTag: 3803e5b2c185f495f8e12f4d40a601abe59d4e89-api-v2