name: Update Manifests on Dispatch

on:
  repository_dispatch:
    types: [update-image]

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.4.1"  # Ensure this version matches your requirements

      - name: Update Kubernetes Deployment with new image using Kustomize
        run: |
          NEW_TAG="${{ github.event.client_payload.image_tag }}"
          ENV_DIR="${{ github.event.client_payload.branch }}"  
          MANIFEST_DIR="./$ENV_DIR"
          cd $MANIFEST_DIR
          kustomize edit set image  271365062139.dkr.ecr.us-east-1.amazonaws.com/vpd-api=$NEW_TAG
          # kustomize build . > updated-deployment.yaml
          # cat updated-deployment.yaml
        # working-directory: ${{ github.workspace }}

      - name: Commit and Push Changes
        run: |
          ENV_DIR="${{ github.event.client_payload.branch }}"  # Reuse the environment directory
          MANIFEST_DIR="./$ENV_DIR"
          cd ${{ github.workspace }}/$MANIFEST_DIR
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Update image tag to $NEW_TAG in $ENV_DIR"
          git push origin HEAD
        env:
         GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
